version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: user_mgmt_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm_network


volumes:
  postgres_data:

networks:
  crm_network:
    driver: bridge